#@see https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Buil Docker images at tag create
on:
  push:
    branchs:
      - develop
  create:
    tags:
      - 1.*  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Tag
        id: get_tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: login
        uses: docker/login-action@v1
        with:
          registry: myregistry
          username: ${{ secretes.DOCKER_UID }}
          password: ${{ secretes.DOCKER_PASSWORD }}
      - name: Build Env
        run: bin/build-env ${{ get_tag .output }}
      - name: Build Images and Push
        run: bin/build-images -f
