#@see https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Buil Docker images at tag create
on:
  push:
    branchs:
      - master
  create:
    tags:
      - 1.*  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo ::set-env name=CURRENT_TAG_VERSION::${GITHUB_REF#refs/*/}
      - name: login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_UID }} --password-stdin
      - name: Build Env
        run: bin/build-env ${{ env.CURRENT_TAG_VERSION }}
      - name: Build Images and Push
        run: bin/build-images -f
