#@see https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Buil Docker Images at tag creation
on:
  create:
    tags:
      - 1.*  
      - 2.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_UID }} --password-stdin
      - name: Build Env
        run: bin/build-env ${GITHUB_REF#refs/*/}
      - name: Debug Env
        run: cat .env
      - name: Build Images and Push
        run: bin/build-images -f
