name: CI
on:
  pull_request:
    branches:
      - master
      - develop
      - verbose
    paths-ignore:
      - '**.md'
      - 'examples/**'
  push:
    branches:
      - develop
      - verbose
    paths-ignore:
      - '**.md'
      - 'examples/**'
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build Env
        run: make build@env

      - name: DC Up
        run: docker-compose -f docker-compose-php.yml up -d --build php-fpm

      - name: DC ps
        run: docker-compose -f docker-compose-php.yml ps

      - name: DC Down
        run: docker-compose -f docker-compose-php.yml down
